language: cpp
dist: trusty

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

install:
  - |
    ## Install Google Test & Google Mock from sources
    git clone https://github.com/google/googletest
    cd googletest
    echo $PWD
    mkdir -p build && cd build
    echo $HOME/.local
    cmake -DBUILD_GTEST=OFF -DBUILD_GMOCK=ON -DCMAKE_INSTALL_PREFIX=$HOME/.local ..
    make -j4
    make install
    cd ../..

script:
  - mkdir -p build && cd build
  - echo $PWD
  - cmake -DGTEST_ROOT=$HOME/.local -DGMOCK_ROOT=$HOME/.local ..
  - make
  - make test