language: cpp

os:
  - linux

dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake-3.0
      - libgtest-dev
      - google-mock

script:
  - mkdir build && cd build
  - CXX=$COMPILER ccmake ..
  - make
  - make test